version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ../src:/var/www/html
      - ../src/vendor:/var/www/html/vendor
      - ../docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - mysql
    networks:
      - tcrcm_network

  web:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ../src/public:/var/www/html/public
      - ../docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - tcrcm_network

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tcrcm
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tcrcm_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - tcrcm_network

  # pg-db:
  #   image: postgres
  #   restart: unless-stopped
  #   container_name: postgres-db
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: tcrcm
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - postgresql_data:/var/lib/postgresql
  #   networks:
  #     - native_php

  # adminer:
  #   image: adminer
  #   container_name: pg-adminer
  #   environment:
  #     ADMINER_DEFAULT_USERNAME: root
  #     ADMINER_DEFAULT_PASSWORD: root
  #   volumes:
  #     - postgresql_data:/var/lib/postgresql
  #   restart: unless-stopped
  #   ports:
  #     - 8082:8080
  #   networks:
  #     - tcrcm_network

networks:
  tcrcm_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  # postgresql_data:
  #   driver: local